language: node_js
node_js:
  - "10"
dist: trusty
env:
  - SMSPVA_KEY=Agy7UgoqMOW3dS1H3QO9NOC5utciHCe9ID5sJjIl
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - sleep 5
  - npm run test
